### ISSUE TITLE
initContainers are overwritten in deployment

### ISSUE THREAD

**Issue by divyangjp** [aws-samples/aws-secret-sidecar-injector#47]
A deployment manifest looks like this

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      annotations:
        secrets.k8s.aws/sidecarInjectorWebhook: enabled
        secrets.k8s.aws/secret-arn: arn:aws:secretsmanager:xxx:000000:secret:sxjxkx-UOBckr
      labels:
        app: nginx
    spec:
      serviceAccountName: aws-eks-secrets-sa
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: tmpconfig
          mountPath: /tmp/config
      initContainers:
      - name: db-init
        image: busybox
        command: ['/bin/sh', '-c']
        args:
         - echo "HELLO WORLD";
```

But when this manifest is applied and pod is `running`,
doing `Kubectl describe pod nginx-deployment-xxxx` has no `db-init` in `initContainers` list. 
There's only `secrets-init-container` in `initContainers` list!

Does the admission-controller webhook overwrites all other `initContainers` !!!
